name: network
version: '${project.version}'
main: plugins.tobisch.com.network.Main
api-version: '1.20'

commands:
  currency:
    permission:
      network.command.currency
  life-saver:
    permission:
      network.command.life-saver
  pay:
    permission:
      network.command.pay
  villager:
    permission:
      network.command.currency